- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy env file"
  copy: 
    dest: ./
    src: ./

- name: "Setup env in backend"
  raw: cp ./.env /home/ubuntu/project3/backend/

- name: Executing node
  shell: |
    cd /home/ubuntu/project3/backend/; pm2 start npm -- run start